In [1]:
# %reset
# TensorFlowとtf.kerasのインポート
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

print(tf.__version__)

2.2.0


JupyterでGPUを使ってるとメモリを一気に食うから以下のスクリプトを走らせる

→https://qiita.com/studio_haneya/items/4dfaf2fb2ac44818e7e0

TensorFlowでGPUに処理をさせる際、デフォルトではありったけのVRAMを確保しようとします。これでメモリー・リークが発生して処理ができなくなるのですが、この「最初にありったけ確保」をやめさせて、必要なだけ徐々に確保する「Memory Glowth」を行わせるには「tf.config.experimental.set_memory_growth(gpu, True)」をコールします。


In [2]:
physical_devices = tf.config.list_physical_devices('GPU')
if len(physical_devices) > 0:
    for device in physical_devices:
        tf.config.experimental.set_memory_growth(device, True)
        print('{} memory growth: {}'.format(device, tf.config.experimental.get_memory_growth(device)))
else:
    print("Not enough GPU hardware devices available")

PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU') memory growth: True


In [3]:
X = tf.constant([[1., 2., 3., 4., 5.], [1., 2., 3., 4., 5.]])
print(X)

tf.Tensor(
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]], shape=(2, 5), dtype=float32)


In [4]:
dense = keras.layers.Dense(32, kernel_initializer='ones')

In [5]:
y = dense(X)
print(y)

tf.Tensor(
[[15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]], shape=(2, 32), dtype=float32)


In [6]:
# x, y, zのデータを持つ点群を想定
X = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(X)

tf.Tensor(
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]], shape=(4, 3), dtype=float32)


In [7]:
dense = keras.layers.Dense(32, kernel_initializer='ones')
# 全部同じ重みのMLPをかける

In [8]:
y = dense(X)
print(y)

tf.Tensor(
[[ 6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.
   6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.  6.]
 [15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.
  15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15. 15.]
 [24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.
  24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24. 24.]
 [33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33.
  33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33.]], shape=(4, 32), dtype=float32)


In [9]:
# max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=2, strides=2, padding='valid')
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=4, strides=1, padding='valid')
# poolsizeを点群数に指定してMaxPooling
reshaped_y = tf.reshape(y, [1, 4, 32])
out = max_pool_1d(reshaped_y)
print(out)
# これで、n個の点群を32の特徴量にすることができた

tf.Tensor(
[[[33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33.
   33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33. 33.]]], shape=(1, 1, 32), dtype=float32)
